server:
  port: 8082

#  database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_hotelservice
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

        #add or import the config-server file of application which is uploaded on github

  config:
    import: configserver:http://localhost:8085


#below code id comping fro github application.yml file

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
